<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann18 (Validite?, Niveau1?, Niveau2?, Niveau3?, Code?, Omschrijving?, begin_geldigheid?, einde_geldigheid?)>
     <!ELEMENT List (ann18+)>
     <!ELEMENT Validite (#PCDATA)>
     <!ELEMENT Niveau1 (#PCDATA)>
     <!ELEMENT Niveau2 (#PCDATA)>
     <!ELEMENT Niveau3 (#PCDATA)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Omschrijving (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>0 - Beroepen bij de strijdkrachten</Niveau1>
<Niveau2>01 - Officieren</Niveau2>
<Niveau3>011 - Officieren</Niveau3>
<Code>0110</Code>
<Omschrijving>Officieren</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>0 - Beroepen bij de strijdkrachten</Niveau1>
<Niveau2>02 - Onderofficieren</Niveau2>
<Niveau3>021 - Onderofficieren</Niveau3>
<Code>0210</Code>
<Omschrijving>Onderofficieren</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>0 - Beroepen bij de strijdkrachten</Niveau1>
<Niveau2>03 - Andere rangen</Niveau2>
<Niveau3>031 - Andere rangen</Niveau3>
<Code>0310</Code>
<Omschrijving>Andere rangen</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>11 - Directeurs van grote ondernemingen,  hogere kaderleden, leden van wetgevende en uitvoerende macht</Niveau2>
<Niveau3>111 - Leden van wetgevende en uitvoerende macht , hogere kaderleden van het openbaar bestuur</Niveau3>
<Code>1111</Code>
<Omschrijving>Leden van de uitvoerende macht en de wetgevende lichamen</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>11 - Directeurs van grote ondernemingen,  hogere kaderleden, leden van wetgevende en uitvoerende macht</Niveau2>
<Niveau3>111 - Leden van wetgevende en uitvoerende macht , hogere kaderleden van het openbaar bestuur</Niveau3>
<Code>1112</Code>
<Omschrijving>Hogere kaderleden van het openbaar bestuur</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>11 - Directeurs van grote ondernemingen,  hogere kaderleden, leden van wetgevende en uitvoerende macht</Niveau2>
<Niveau3>111 - Leden van wetgevende en uitvoerende macht , hogere kaderleden van het openbaar bestuur</Niveau3>
<Code>1113</Code>
<Omschrijving>Traditionele dorpshoofden</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>11 - Directeurs van grote ondernemingen,  hogere kaderleden, leden van wetgevende en uitvoerende macht</Niveau2>
<Niveau3>111 - Leden van wetgevende en uitvoerende macht , hogere kaderleden van het openbaar bestuur</Niveau3>
<Code>1114</Code>
<Omschrijving>Beleidsvoerende medewerkers van belangenorganisaties</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>11 - Directeurs van grote ondernemingen,  hogere kaderleden, leden van wetgevende en uitvoerende macht</Niveau2>
<Niveau3>112 - Directeurs van grote ondernemingen</Niveau3>
<Code>1120</Code>
<Omschrijving>Directeurs van grote ondernemingen</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>12 - Managers op administratief en commercieel gebied</Niveau2>
<Niveau3>121 -  Managers op het gebied van zakelijke dienstverlening  en op administratief gebied</Niveau3>
<Code>1211</Code>
<Omschrijving>Managers op financieel gebied</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>12 - Managers op administratief en commercieel gebied</Niveau2>
<Niveau3>121 -  Managers op het gebied van zakelijke dienstverlening  en op administratief gebied</Niveau3>
<Code>1212</Code>
<Omschrijving>Managers op het gebied van  human resources</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>12 - Managers op administratief en commercieel gebied</Niveau2>
<Niveau3>121 -  Managers op het gebied van zakelijke dienstverlening  en op administratief gebied</Niveau3>
<Code>1213</Code>
<Omschrijving>Managers op het gebied van beleid en planning</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>12 - Managers op administratief en commercieel gebied</Niveau2>
<Niveau3>121 -  Managers op het gebied van zakelijke dienstverlening  en op administratief gebied</Niveau3>
<Code>1219</Code>
<Omschrijving>Managers op het gebied van zakelijke dienstverlening  en op administratief gebied, niet elders geclassificeerd</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>12 - Managers op administratief en commercieel gebied</Niveau2>
<Niveau3>122 -  Managers op het gebied van verkoop, marketing, reclame, public relations en  speur- en ontwikkelingswerk</Niveau3>
<Code>1221</Code>
<Omschrijving>Managers op het gebied van verkoop en marketing</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>12 - Managers op administratief en commercieel gebied</Niveau2>
<Niveau3>122 -  Managers op het gebied van verkoop, marketing, reclame, public relations en  speur- en ontwikkelingswerk</Niveau3>
<Code>1222</Code>
<Omschrijving>Managers op het gebied van reclame en public relations</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>12 - Managers op administratief en commercieel gebied</Niveau2>
<Niveau3>122 -  Managers op het gebied van verkoop, marketing, reclame, public relations en  speur- en ontwikkelingswerk</Niveau3>
<Code>1223</Code>
<Omschrijving>Managers op het gebied van speur- en ontwikkelingswerk</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>131 -  Managers op het gebied van land-en bosbouw , visserij en aquacultuur</Niveau3>
<Code>1311</Code>
<Omschrijving>Managers op het gebied van  land- en bosbouw</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>131 -  Managers op het gebied van land-en bosbouw , visserij en aquacultuur</Niveau3>
<Code>1312</Code>
<Omschrijving>Managers op het gebied van aquacultuur en visserij</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>132 -  Managers in de industrie, de delfstoffenwinning, de bouwnijverheid en de logistiek</Niveau3>
<Code>1321</Code>
<Omschrijving>Managers in de industrie</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>132 -  Managers in de industrie, de delfstoffenwinning, de bouwnijverheid en de logistiek</Niveau3>
<Code>1322</Code>
<Omschrijving>Managers in de  delfstoffenwinning</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>132 -  Managers in de industrie, de delfstoffenwinning, de bouwnijverheid en de logistiek</Niveau3>
<Code>1323</Code>
<Omschrijving>Managers in de bouwnijverheid</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>132 -  Managers in de industrie, de delfstoffenwinning, de bouwnijverheid en de logistiek</Niveau3>
<Code>1324</Code>
<Omschrijving>Managers op het gebied van logistiek en aanverwante diensten</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>133 -  Managers op het gebied van informatie- en communicatietechnologie (ICT)</Niveau3>
<Code>1330</Code>
<Omschrijving>Managers op het gebied van informatie- en communicatietechnologie (ICT)</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>134 -  Managers op het gebied van professionele diensten</Niveau3>
<Code>1341</Code>
<Omschrijving>Managers op het gebied van kinderopvang</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>134 -  Managers op het gebied van professionele diensten</Niveau3>
<Code>1342</Code>
<Omschrijving>Managers op het gebied van menselijke gezondheidszorg</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>134 -  Managers op het gebied van professionele diensten</Niveau3>
<Code>1343</Code>
<Omschrijving>Managers op het gebied van ouderenzorg</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>134 -  Managers op het gebied van professionele diensten</Niveau3>
<Code>1344</Code>
<Omschrijving>Managers op het gebied van maatschappelijke dienstverlening</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>134 -  Managers op het gebied van professionele diensten</Niveau3>
<Code>1345</Code>
<Omschrijving>Managers op het gebied van onderwijs</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>134 -  Managers op het gebied van professionele diensten</Niveau3>
<Code>1346</Code>
<Omschrijving>Filiaalhouders op het gebied van financiële dienstverlening en verzekeringen</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>13 - Managers op het gebied van productie en gespecialiseerde diensten</Niveau2>
<Niveau3>134 -  Managers op het gebied van professionele diensten</Niveau3>
<Code>1349</Code>
<Omschrijving>Managers op het gebied van professionele diensten, niet elders geclassificeerd</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>14 - Managers in het hotel en restaurantwezen, in de detail- en groothandel en op het gebied van andere diensten</Niveau2>
<Niveau3>141 -  Hotel- en restaurantmanagers</Niveau3>
<Code>1411</Code>
<Omschrijving>Hotelmanagers</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>14 - Managers in het hotel en restaurantwezen, in de detail- en groothandel en op het gebied van andere diensten</Niveau2>
<Niveau3>141 -  Hotel- en restaurantmanagers</Niveau3>
<Code>1412</Code>
<Omschrijving>Restaurantmanagers</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>14 - Managers in het hotel en restaurantwezen, in de detail- en groothandel en op het gebied van andere diensten</Niveau2>
<Niveau3>142 -  Managers in de detail- en groothandel</Niveau3>
<Code>1420</Code>
<Omschrijving>Managers in de detail- en groothandel</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>14 - Managers in het hotel en restaurantwezen, in de detail- en groothandel en op het gebied van andere diensten</Niveau2>
<Niveau3>143 -  Managers op het gebied van andere diensten</Niveau3>
<Code>1431</Code>
<Omschrijving>Managers op het gebied van sport en recreatie en bij culturele centra</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>1 - Managers</Niveau1>
<Niveau2>14 - Managers in het hotel en restaurantwezen, in de detail- en groothandel en op het gebied van andere diensten</Niveau2>
<Niveau3>143 -  Managers op het gebied van andere diensten</Niveau3>
<Code>1439</Code>
<Omschrijving>Managers op het gebied van diensten, niet elders geclassificeerd</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>211 -  Natuur- en aardwetenschappers</Niveau3>
<Code>2111</Code>
<Omschrijving>Natuurkundigen en  sterrenkundigen</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>211 -  Natuur- en aardwetenschappers</Niveau3>
<Code>2112</Code>
<Omschrijving>Meteorologen</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>211 -  Natuur- en aardwetenschappers</Niveau3>
<Code>2113</Code>
<Omschrijving>Scheikundigen</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>211 -  Natuur- en aardwetenschappers</Niveau3>
<Code>2114</Code>
<Omschrijving>Geologen en geofysici</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>212 -  Wiskundigen, actuarissen en statistici</Niveau3>
<Code>2120</Code>
<Omschrijving>Wiskundigen, actuarissen en statistici</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>213 -  Biowetenschappers</Niveau3>
<Code>2131</Code>
<Omschrijving>Biologen, botanici, zoölogen en dergelijke</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>213 -  Biowetenschappers</Niveau3>
<Code>2132</Code>
<Omschrijving>Adviseurs op het gebied van landbouw, bosbouw en visserij</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>213 -  Biowetenschappers</Niveau3>
<Code>2133</Code>
<Omschrijving>Milieudeskundigen</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>214 -  Ingenieurs (met uitzondering van elektrotechnisch ingenieurs)</Niveau3>
<Code>2141</Code>
<Omschrijving>Industrieel ingenieurs en productie-ingenieurs</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>214 -  Ingenieurs (met uitzondering van elektrotechnisch ingenieurs)</Niveau3>
<Code>2142</Code>
<Omschrijving>Burgerlijk ingenieurs</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>214 -  Ingenieurs (met uitzondering van elektrotechnisch ingenieurs)</Niveau3>
<Code>2143</Code>
<Omschrijving>Milieu-ingenieurs</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>214 -  Ingenieurs (met uitzondering van elektrotechnisch ingenieurs)</Niveau3>
<Code>2144</Code>
<Omschrijving>Ingenieurs mechanica</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>214 -  Ingenieurs (met uitzondering van elektrotechnisch ingenieurs)</Niveau3>
<Code>2145</Code>
<Omschrijving>Ingenieurs scheikunde</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>214 -  Ingenieurs (met uitzondering van elektrotechnisch ingenieurs)</Niveau3>
<Code>2146</Code>
<Omschrijving>Mijningenieurs, metallurgen en dergelijke</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>214 -  Ingenieurs (met uitzondering van elektrotechnisch ingenieurs)</Niveau3>
<Code>2149</Code>
<Omschrijving>Ingenieurs, niet elders geclassificeerd</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>215 -  Ingenieurs op het gebied van de elektrotechnologie</Niveau3>
<Code>2151</Code>
<Omschrijving>Ingenieurs elektriciteit</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>215 -  Ingenieurs op het gebied van de elektrotechnologie</Niveau3>
<Code>2152</Code>
<Omschrijving>Ingenieurs elektronica</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>215 -  Ingenieurs op het gebied van de elektrotechnologie</Niveau3>
<Code>2153</Code>
<Omschrijving>Ingenieurs telecommunicatie</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>216 -  Architecten, planologen, landmeters en designers</Niveau3>
<Code>2161</Code>
<Omschrijving>Bouwkundig architecten</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>216 -  Architecten, planologen, landmeters en designers</Niveau3>
<Code>2162</Code>
<Omschrijving>Landschapsarchitecten</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>216 -  Architecten, planologen, landmeters en designers</Niveau3>
<Code>2163</Code>
<Omschrijving>Product- en kledingdesigners</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>216 -  Architecten, planologen, landmeters en designers</Niveau3>
<Code>2164</Code>
<Omschrijving>Stedenbouwkundigen en verkeersdeskundigen</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>216 -  Architecten, planologen, landmeters en designers</Niveau3>
<Code>2165</Code>
<Omschrijving>Cartografen en landmeters</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>
<Validite>ISCO08 - nomenclatuur geldig voor de arbeidsongevallen vanaf 2012</Validite>
<Niveau1>2 - Intellectuele, wetenschappelijke en artistieke beroepen</Niveau1>
<Niveau2>21 - Wetenschappers en ingenieurs</Niveau2>
<Niveau3>216 -  Architecten, planologen, landmeters en designers</Niveau3>
<Code>2166</Code>
<Omschrijving>Grafisch en multimedia designers</Omschrijving>
<begin_geldigheid>01/01/2012</begin_geldigheid>
<einde_geldigheid>31/12/9999</einde_geldigheid>
</ann18>
<ann18>