<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann9 (Ventilation?, Categorie?, Code?, Leeftijd?, Fonction?, begin_geldigheid?, einde_geldigheid?)>
     <!ELEMENT List (ann9+)>
     <!ELEMENT Ventilation (#PCDATA)>
     <!ELEMENT Categorie (#PCDATA)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Leeftijd (#PCDATA)>
     <!ELEMENT Fonction (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>27</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Porteurs de bagages</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>32</Code>
<Leeftijd>15</Leeftijd>
<Fonction>Chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>33</Code>
<Leeftijd>16</Leeftijd>
<Fonction>Chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>34</Code>
<Leeftijd>17</Leeftijd>
<Fonction>Adjoint chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>35</Code>
<Leeftijd>18</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>36</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>37</Code>
<Leeftijd>20</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>38</Code>
<Leeftijd>-,21,-,18,18,-,-</Leeftijd>
<Fonction>Voiturier, Portier, Bagagiste, Valet de chambre, Femme de chambre, Préposée à la toilette, Préposée au vestiaire, Autres travailleurs</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>39</Code>
<Leeftijd>21</Leeftijd>
<Fonction>Concierge</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>40</Code>
<Leeftijd>23</Leeftijd>
<Fonction>Chef concierge</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>41</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Valet de chambre, femme de chambre</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>43</Code>
<Leeftijd>15</Leeftijd>
<Fonction>Apprenti de salle</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>44</Code>
<Leeftijd>16</Leeftijd>
<Fonction>Apprenti de salle</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>45</Code>
<Leeftijd>17</Leeftijd>
<Fonction>Commis débarrasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>46</Code>
<Leeftijd>18</Leeftijd>
<Fonction>Commis de suite, Commis de suite/ banquet, Commis barman, Commis d'étage</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>47</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Commis de rang, Garçon de banquet</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>48</Code>
<Leeftijd>20</Leeftijd>
<Fonction>1/2 chef de rang restaurant, 1/2 chef de rang banquet, Commis barman</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>49</Code>
<Leeftijd>21,21,21,21,21,21,22,-</Leeftijd>
<Fonction>Garçon de restaurant, Chef de rang restaurant, Garçon de banquet, Chef de rang banquet, Garçon de brasserie, taverne, bistro,  Garçon de café, Barman, Garçon d'étage</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>50</Code>
<Leeftijd>22,22,22,-</Leeftijd>
<Fonction>Premier chef de rang, Sommelier, Premier chef de rang banquet, Responsable barman</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>51</Code>
<Leeftijd>23</Leeftijd>
<Fonction>Maître d'hôtel restaurant, Maître d'hôtel banquet, Maître d'hôtel roomservice</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>52</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Assistant maître d'hôtel restaurant, Assistant maître d'hôtel banquet, Assistant maître d'hôtel roomservice</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>16</Categorie>
<Code>98</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Travailleur occasionnel dans l'Horeca</Fonction>
<begin_geldigheid>01/07/2003</begin_geldigheid>
<einde_geldigheid>30/06/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>27</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Porteurs de bagages</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>32</Code>
<Leeftijd>15</Leeftijd>
<Fonction>Chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>33</Code>
<Leeftijd>16</Leeftijd>
<Fonction>Chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>34</Code>
<Leeftijd>17</Leeftijd>
<Fonction>Adjoint chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>35</Code>
<Leeftijd>18</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>36</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>37</Code>
<Leeftijd>20</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>38</Code>
<Leeftijd>-,21,-,18,18,-,-</Leeftijd>
<Fonction>Voiturier, Portier, Bagagiste, Valet de chambre, Femme de chambre, Préposée à la toilette, Préposée au vestiaire, Autres travailleurs</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>39</Code>
<Leeftijd>21</Leeftijd>
<Fonction>Concierge</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>40</Code>
<Leeftijd>23</Leeftijd>
<Fonction>Chef concierge</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>41</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Valet de chambre, femme de chambre</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>43</Code>
<Leeftijd>15</Leeftijd>
<Fonction>Apprenti de salle</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>44</Code>
<Leeftijd>16</Leeftijd>
<Fonction>Apprenti de salle</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>45</Code>
<Leeftijd>17</Leeftijd>
<Fonction>Commis débarrasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>46</Code>
<Leeftijd>18</Leeftijd>
<Fonction>Commis de suite, Commis de suite/ banquet, Commis barman, Commis d'étage</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>47</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Commis de rang, Garçon de banquet</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>48</Code>
<Leeftijd>20</Leeftijd>
<Fonction>1/2 chef de rang restaurant, 1/2 chef de rang banquet, Commis barman</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>49</Code>
<Leeftijd>21,21,21,21,21,21,22,-</Leeftijd>
<Fonction>Garçon de restaurant, Chef de rang restaurant, Garçon de banquet, Chef de rang banquet, Garçon de brasserie, taverne, bistro, Garçon de café, Barman, Garçon d'étage</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>50</Code>
<Leeftijd>22</Leeftijd>
<Fonction>Premier chef de rang, Sommelier, Premier chef de rang banquet, Responsable barman</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>51</Code>
<Leeftijd>23</Leeftijd>
<Fonction>Maître d'hôtel restaurant, Maître d'hôtel banquet, Maître d'hôtel roomservice</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>52</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Assistant maître d'hôtel restaurant, Assistant maître d'hôtel banquet, Assistant maître d'hôtel roomservice</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>17</Categorie>
<Code>98</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Travailleur occasionnel dans l'Horeca</Fonction>
<begin_geldigheid>01/07/2003</begin_geldigheid>
<einde_geldigheid>30/06/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>19</Categorie>
<Code>81</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Marins pêcheurs : équipage des bâtiments de pêche à l'exception des apprentis mousses</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>19</Categorie>
<Code>82</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Marins pêcheurs : apprentis mousses</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>20</Categorie>
<Code>20</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Ouvreuses et préposées au vestiaire occupées dans les théâtres</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>20</Categorie>
<Code>25</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Ouvreuses et préposées au vestiaire occupées dans les salles de spectacles cinématographiques pendant au moins 40 heures/semaine</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>20</Categorie>
<Code>26</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Ouvreuses et préposées au vestiaire occupées dans les autres entreprises de spectacle pendant moins de 40 heures/semaine ou occupées dans les autres entreprises que des théâtres ou préposés à la toilette</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>20</Categorie>
<Code>29</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Tous les autres travailleurs rémunérés totalement ou partiellement au pourboire</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>23</Categorie>
<Code>20</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Ouvreuses et préposées au vestiaire occupées dans les théâtres</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>23</Categorie>
<Code>25</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Ouvreuses et préposées au vestiaire occupées dans les salles de spectacles cinématographiques pendant au moins 40 heures/semaine</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>23</Categorie>
<Code>26</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Ouvreuses et préposées au vestiaire occupées dans les autres entreprises de spectacle pendant moins de 40 heures/semaine ou occupées dans les autres entreprises que des théâtres ou préposés à la toilette</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>23</Categorie>
<Code>29</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Tous les autres travailleurs rémunérés totalement ou partiellement au pourboire</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>68</Categorie>
<Code>28</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Autres chauffeurs de taxis-camionnettes</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>68</Categorie>
<Code>30</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Chauffeurs de taxis-camionnettes : chauffeurs occupés à raison au maximum de 6 heures/jour et 30 heures/semaine</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>97</Categorie>
<Code>91</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Travailleurs occasionnels dans l'agriculture</Fonction>
<begin_geldigheid>01/01/2007</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>97</Categorie>
<Code>98</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Travailleur occasionnel dans l'Horeca</Fonction>
<begin_geldigheid>01/01/2004</begin_geldigheid>
<einde_geldigheid>30/06/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>97</Categorie>
<Code>99</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Travailleurs occasionnels dans  l'agriculture (jusqu'au 4/2006) et l'horticulture</Fonction>
<begin_geldigheid>01/07/2004</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>27</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Porteurs de bagages</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>32</Code>
<Leeftijd>15</Leeftijd>
<Fonction>Chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>33</Code>
<Leeftijd>16</Leeftijd>
<Fonction>Chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>34</Code>
<Leeftijd>17</Leeftijd>
<Fonction>Adjoint chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>35</Code>
<Leeftijd>18</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>36</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>37</Code>
<Leeftijd>20</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>38</Code>
<Leeftijd>-,21,-,18,18,-,-</Leeftijd>
<Fonction>Voiturier, Portier,Bagagiste, Valet de chambre, Femme de chambre, Préposée à la toilette, Préposée au vestiaire, Autres travailleurs</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>39</Code>
<Leeftijd>21</Leeftijd>
<Fonction>Concierge</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>40</Code>
<Leeftijd>23</Leeftijd>
<Fonction>Chef concierge</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>41</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Valet de chambre, femme de chambre</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>43</Code>
<Leeftijd>15</Leeftijd>
<Fonction>Apprenti de salle</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>44</Code>
<Leeftijd>16</Leeftijd>
<Fonction>Apprenti de salle</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>45</Code>
<Leeftijd>17</Leeftijd>
<Fonction>Commis débarrasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>46</Code>
<Leeftijd>18</Leeftijd>
<Fonction>Commis de suite, Commis de suite banquet, Commis barman, Commis d'étage</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>47</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Commis de rang, Garçon de banquet</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>48</Code>
<Leeftijd>20</Leeftijd>
<Fonction>1/2 chef de rang, 1/2 chef de rang banquet, Commis barman</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>49</Code>
<Leeftijd>21,21,21,21,21,21,22,-</Leeftijd>
<Fonction>Garçon de restaurant, Chef de rang restaurant, Garçon de banquet, Chef de rang banquet, Garçon de brasserie, taverne, bistro, Garçon de café, Barman, Garçon d'étage</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>50</Code>
<Leeftijd>22,22,22,-</Leeftijd>
<Fonction>Premier chef de rang, Sommelier, Premier chef de rang banquet, Responsable barman</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>51</Code>
<Leeftijd>23</Leeftijd>
<Fonction>Maître d'hôtel restaurant, Maître d'hôtel banquet, Maître d'hôtel roomservice</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>146</Categorie>
<Code>52</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Assistant maître d'hôtel restaurant, Assistant maître d'hôtel banquet, Assistant maître d'hôtel roomservice</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>158</Categorie>
<Code>27</Code>
<Leeftijd>-</Leeftijd>
<Fonction>Porteurs de bagages</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>158</Categorie>
<Code>32</Code>
<Leeftijd>15</Leeftijd>
<Fonction>Chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>158</Categorie>
<Code>33</Code>
<Leeftijd>16</Leeftijd>
<Fonction>Chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>158</Categorie>
<Code>34</Code>
<Leeftijd>17</Leeftijd>
<Fonction>Adjoint chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>158</Categorie>
<Code>35</Code>
<Leeftijd>18</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>158</Categorie>
<Code>36</Code>
<Leeftijd>19</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>158</Categorie>
<Code>37</Code>
<Leeftijd>20</Leeftijd>
<Fonction>Chef chasseur</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>158</Categorie>
<Code>38</Code>
<Leeftijd>-,21,-,18,18,-,-</Leeftijd>
<Fonction>Voiturier, Portier, Bagagiste, Valet de chambre, Femme de chambre, Préposée à la toilette, Préposée au vestiaire, Autres travailleurs</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>
<Ventilation>Numéros de fonction valides jusqu'au 2007/1</Ventilation>
<Categorie>158</Categorie>
<Code>39</Code>
<Leeftijd>21</Leeftijd>
<Fonction>Concierge</Fonction>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2007</einde_geldigheid>
</ann9>
<ann9>