<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Verminderingscodes -->
<!-- Codes déductions -->
<!DOCTYPE List [
     <!ELEMENT ann4 (CodeDMFA?, Description?, Vanaf?, Tot?, Ded_FedRegFR?
            , Ded_FlemishRegFR?, Ded_BxlRegFR?, Ded_WallNoGermanRegFR?
            , Ded_WallGermanRegFR?, CalcBaseFr?, AmountFr?, StartRightFr?
            , MnthCostFr?, InssNbrReplFr?, InssNbrAuthFr?, OrigAttFr?
            , LinkBlocFr?, PresBlcDetFr?)>
     <!ELEMENT List (ann4+)>
     <!ELEMENT CodeDMFA (#PCDATA)>
     <!ELEMENT Description (#PCDATA)>
     <!ELEMENT Vanaf (#PCDATA)>
     <!ELEMENT Tot (#PCDATA)>
     <!ELEMENT Ded_FedRegFR (#PCDATA)>
     <!ELEMENT Ded_FlemishRegFR (#PCDATA)>
     <!ELEMENT Ded_BxlRegFR (#PCDATA)>
     <!ELEMENT Ded_WallNoGermanRegFR (#PCDATA)>
     <!ELEMENT Ded_WallGermanRegFR (#PCDATA)>
     <!ELEMENT CalcBaseFr (#PCDATA)>
     <!ELEMENT AmountFr (#PCDATA)>
     <!ELEMENT StartRightFr (#PCDATA)>
     <!ELEMENT MnthCostFr (#PCDATA)>
     <!ELEMENT InssNbrReplFr (#PCDATA)>
     <!ELEMENT InssNbrAuthFr (#PCDATA)>
     <!ELEMENT OrigAttFr (#PCDATA)>
     <!ELEMENT LinkBlocFr (#PCDATA)>
     <!ELEMENT PresBlcDetFr (#PCDATA)>
]>
<List>
    <ann4>
        <CodeDMFA>0001</CodeDMFA>
        <Description>Réduction des cotisations personnelles pour les travailleurs ayant un bonus à l'emploi</Description>
        <Vanaf>2000/1</Vanaf>
        <Tot>9999/4</Tot>
        <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
        <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
        <Ded_BxlRegFR>-</Ded_BxlRegFR>
        <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
        <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
        <CalcBaseFr>Interdit</CalcBaseFr>
        <AmountFr>Obligatoire</AmountFr>
        <StartRightFr>Interdit</StartRightFr>
        <MnthCostFr>Interdit</MnthCostFr>
        <InssNbrReplFr>Interdit</InssNbrReplFr>
        <InssNbrAuthFr>Interdit</InssNbrAuthFr>
        <OrigAttFr>Optionnel</OrigAttFr>
        <LinkBlocFr>Ligne travailleur</LinkBlocFr>
        <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
        <CodeDMFA>0501</CodeDMFA>
        <Description>Réduction des cotisations personnelles pour le secteur du dragage</Description>
        <Vanaf>2000/1</Vanaf>
        <Tot>2014/2</Tot>
        <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
        <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
        <Ded_BxlRegFR>-</Ded_BxlRegFR>
        <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
        <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
        <CalcBaseFr>Obligatoire</CalcBaseFr>
        <AmountFr>Obligatoire</AmountFr>
        <StartRightFr>Interdit</StartRightFr>
        <MnthCostFr>Interdit</MnthCostFr>
        <InssNbrReplFr>Interdit</InssNbrReplFr>
        <InssNbrAuthFr>Interdit</InssNbrAuthFr>
        <OrigAttFr>Optionnel</OrigAttFr>
        <LinkBlocFr>Ligne travailleur</LinkBlocFr>
        <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
        <CodeDMFA>0600</CodeDMFA>
        <Description>Réduction des cotisations personnelles pour les travailleurs licenciés dans le cadre d'une restructuration - contrat de travail conclu avant le 1/1/2007</Description>
        <Vanaf>2004/3</Vanaf>
        <Tot>2007/2</Tot>
        <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
        <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
        <Ded_BxlRegFR>-</Ded_BxlRegFR>
        <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
        <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
        <CalcBaseFr>Interdit</CalcBaseFr>
        <AmountFr>Obligatoire</AmountFr>
        <StartRightFr>Interdit</StartRightFr>
        <MnthCostFr>Interdit</MnthCostFr>
        <InssNbrReplFr>Interdit</InssNbrReplFr>
        <InssNbrAuthFr>Interdit</InssNbrAuthFr>
        <OrigAttFr>Optionnel</OrigAttFr>
        <LinkBlocFr>Ligne travailleur</LinkBlocFr>
        <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>0601</CodeDMFA>
    <Description>Réduction des cotisations personnelles pour les travailleurs licenciés dans le cadre d'une restructuration</Description>
    <Vanaf>2007/1</Vanaf>
    <Tot>9999/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>0610</CodeDMFA>
    <Description>Bonus sport</Description>
    <Vanaf>2022/1</Vanaf>
    <Tot>9999/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Interdit</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>0611</CodeDMFA>
    <Description>Réduction des cotisations personnelles pour les pensionnés qui travaillent dans le secteur de la santé</Description>
    <Vanaf>2022/3</Vanaf>
    <Tot>2022/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Interdit</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1001</CodeDMFA>
    <Description>Réduction structurelle</Description>
    <Vanaf>1999/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Interdit</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1101</CodeDMFA>
    <Description>Plan d'embauche pour demandeurs d'emploi répondant à la condition des 12 mois</Description>
    <Vanaf>1995/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1101</CodeDMFA>
    <Description>Période transitoire.  Plan d'embauche pour demandeurs d'emploi répondant à la condition des 12 mois</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2004/1</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1102</CodeDMFA>
    <Description>Plan d'embauche pour demandeurs d'emploi répondant à la condition des 24 mois</Description>
    <Vanaf>1995/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1102</CodeDMFA>
    <Description>Période transitoire.  Plan d'embauche pour demandeurs d'emploi répondant à la condition des 24 mois</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2004/1</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1103</CodeDMFA>
    <Description>Plan d'embauche pour demandeurs d'emploi dans les entreprises d'insertion</Description>
    <Vanaf>1996/3</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1103</CodeDMFA>
    <Description>Période transitoire.  Plan d'embauche pour demandeurs d'emploi dans les entreprises d'insertion</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2007/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1104</CodeDMFA>
    <Description>Plan d'embauche pour demandeurs d'emploi de plus de 50 ans</Description>
    <Vanaf>1996/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1105</CodeDMFA>
    <Description>Plan d'embauche pour demandeurs d'emploi répondant à la condition des 12 mois (&gt; 45 ans)</Description>
    <Vanaf>2000/3</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1105</CodeDMFA>
    <Description>Période transitoire.  Plan d'embauche pour demandeurs d'emploi répondant à la condition des 12 mois (&gt; 45 ans)</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2008/1</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1106</CodeDMFA>
    <Description>Plan d'embauche pour demandeurs d'emploi répondant à la condition des 24 mois (&gt; 45 ans)</Description>
    <Vanaf>2000/3</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1106</CodeDMFA>
    <Description>Période transitoire.  Plan d'embauche pour demandeurs d'emploi répondant à la condition des 24 mois (&gt; 45 ans)</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2008/1</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1111</CodeDMFA>
    <Description>Plan Activa - promotion de mise à l'emploi des demandeurs d'emploi de longue durée - 75%</Description>
    <Vanaf>2002/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1111</CodeDMFA>
    <Description>Période transitoire. Plan Activa conclu avant le 1.1.2004 - promotion de mise à l'emploi des demandeurs d'emploi de longue durée - 75%</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2008/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1112</CodeDMFA>
    <Description>Plan Activa - promotion de mise à l'emploi des demandeurs d'emploi de longue durée - 100%</Description>
    <Vanaf>2002/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1112</CodeDMFA>
    <Description>Période transitoire.  Plan Activa conclu avant le 1.1.2004 - promotion de mise à l'emploi des demandeurs d'emploi de longue durée - 100%</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2008/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1121</CodeDMFA>
    <Description>Plan plus un</Description>
    <Vanaf>1994/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Optionnel</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1121</CodeDMFA>
    <Description>Période transitoire.  Plan plus un</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2006/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1122</CodeDMFA>
    <Description>Plan plus deux</Description>
    <Vanaf>1997/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Optionnel</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1122</CodeDMFA>
    <Description>Période transitoire.  Plan plus deux</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2006/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1123</CodeDMFA>
    <Description>Plan plus trois</Description>
    <Vanaf>1997/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Optionnel</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1123</CodeDMFA>
    <Description>Période transitoire.  Plan plus trois</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2005/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1124</CodeDMFA>
    <Description>Plan plus un - ancien intérimaire</Description>
    <Vanaf>1998/4</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Optionnel</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1124</CodeDMFA>
    <Description>Période transitoire.  Plan plus un - ancien intérimaire</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2006/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1125</CodeDMFA>
    <Description>Plan plus deux - ancien intérimaire</Description>
    <Vanaf>1998/4</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Optionnel</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1125</CodeDMFA>
    <Description>Période transitoire.  Plan plus deux - ancien intérimaire</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2006/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1126</CodeDMFA>
    <Description>Plan plus trois - ancien intérimaire</Description>
    <Vanaf>1998/4</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Optionnel</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1126</CodeDMFA>
    <Description>Période transitoire.  Plan plus trois - ancien intérimaire</Description>
    <Vanaf>2004/1</Vanaf>
    <Tot>2005/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Interdit</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Obligatoire</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1131</CodeDMFA>
    <Description>Réduction AR n°483 - Réduction pour l'engagement d'un premier travailleur en qualité de personnel de maison (gens de maison (ouvriers et employés); domestiques)</Description>
    <Vanaf>1987/1</Vanaf>
    <Tot>2013/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>
    <Ded_BxlRegFR>-</Ded_BxlRegFR>
    <Ded_WallNoGermanRegFR>-</Ded_WallNoGermanRegFR>
    <Ded_WallGermanRegFR>-</Ded_WallGermanRegFR>
    <CalcBaseFr>Obligatoire</CalcBaseFr>
    <AmountFr>Obligatoire</AmountFr>
    <StartRightFr>Interdit</StartRightFr>
    <MnthCostFr>Interdit</MnthCostFr>
    <InssNbrReplFr>Interdit</InssNbrReplFr>
    <InssNbrAuthFr>Interdit</InssNbrAuthFr>
    <OrigAttFr>Optionnel</OrigAttFr>
    <LinkBlocFr>Occupation de la ligne travailleur</LinkBlocFr>
    <PresBlcDetFr>Non</PresBlcDetFr>
    </ann4>
    <ann4>
    <CodeDMFA>1141</CodeDMFA>
    <Description>Activation des allocations de chômage</Description>
    <Vanaf>1998/1</Vanaf>
    <Tot>2003/4</Tot>
    <Ded_FedRegFR>Fédérale</Ded_FedRegFR>
    <Ded_FlemishRegFR>-</Ded_FlemishRegFR>