<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann11 (Code?, Description?, begin_geldigheid?, einde_geldigheid?)>
     <!ELEMENT List (ann11+)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Description (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>
<ann11>
<Code>AADD501</Code>
<Description>Demande enrichie d'une déclaration</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ACRF001</Code>
<Description>Accusé de réception</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>AOAT001</Code>
<Description>Accidents de Travail scénario 1 - déclaration d'un accident de travail</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>AOAT002</Code>
<Description>Accidents de Travail scénario 2 - rapport mensuel</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>AOAT003</Code>
<Description>Accidents de Travail scénario 3 - déclaration d'une reprise de travail</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>AVDDTUP</Code>
<Description>Déclaration de modification relative à une déclaration de travaux</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>AVWDDT</Code>
<Description>Déclaration de travaux</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>BEWARE</Code>
<Description>Notification reprenant les informations comptables relatives aux modifications de la déclaration multifonctionnelle d'un employeur immatriculé à l'ONSS et, le cas échéant, les données relatives à l'avis rectificatif de cotisations qui en a résulté.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>BEWLST</Code>
<Description>Liste de contrôle des notifications Beware envoyées le jour précédent à la maison mère d'un SSA.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>BZMP001</Code>
<Description>Maladies professionnelles scénario 1 - demande mandatée - écartement d'une travailleuse enceinte - secteur privé</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/06/2011</einde_geldigheid>
</ann11>
<ann11>
<Code>CDHG001</Code>
<Description>Déclaration de l'attestation Historique de carrière</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>DEFI001</Code>
<Description>Décision finale</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>DIMONA</Code>
<Description>Déclaration immédiate à l'emploi</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>DMFA</Code>
<Description>Déclaration multifonctionnelle trimestrielle concernant un employeur immatriculé à l'ONSS</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>DMFADB</Code>
<Description>Réponse à une demande de consultation de la dernière situation d'une déclaration multifonctionnelle</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>DMFANOT</Code>
<Description>Notification de modification relative à une déclaration multifonctionnelle</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>DMFAPID</Code>
<Description>Données d'identification dans la DB DmfA d'une déclaration DmfA originale</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>DMFAPPL</Code>
<Description>Déclaration multifonctionnelle trimestrielle concernant une administration provinciale ou locale</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>DMFAREQ</Code>
<Description>Demande de consultation de la dernière situation d'une déclaration multifonctionnelle</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>DMFAUPD</Code>
<Description>Déclaration de modification relative à une déclaration multifonctionnelle concernant un employeur immatriculé à l'ONSS</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ECAROAN</Code>
<Description>Réponse à une demande de consultation des données ECARO d'une personne</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ECARORQ</Code>
<Description>Demande de consultation des données ECARO d'une personne</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ECOUDAN</Code>
<Description>Réponse à une demande de consultation des jours de chômage économique hors du secteur de la construction</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ECOUDRQ</Code>
<Description>Demande de consultation des jours de chômage économique hors du secteur de la construction</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>FINO001</Code>
<Description>Note reprenant les informations relatives aux transactions financières et au processus de calcul des provisions forfaitaires ou procentuelles dont les employeurs sont redevables (ou pas) envers l'ONSS.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>FINO002</Code>
<Description>Note reprenant les informations relatives aux transactions financières et au processus de calcul des provisions forfaitaires et/ou procentuelles dont les employeurs sont redevables envers l'ONSS.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>FINO003</Code>
<Description>Note reprenant les informations relatives aux transactions financières et aux processus des rappels DGII/397 à payer par les employeurs ONSS.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>FINO004</Code>
<Description>Note reprenant les informations relatives aux transactions financières et aux processus des rappels DGII/398 à payer par les employeurs ONSS.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/06/2019</einde_geldigheid>
</ann11>
<ann11>
<Code>FINO014</Code>
<Description>Note reprenant les informations relatives aux transactions financières et au processus de mise en demeure</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>FISI001</Code>
<Description>Note reprenant les situations relatives aux paiements du trimestre courant des employeurs ONSS.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>FISI002</Code>
<Description>Communication des dettes sociales des employeurs ONSS</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>FISI003</Code>
<Description>Communication trimestrielle des dettes sociales des employeurs Titres Services ONSS</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>IDFLUX</Code>
<Description>Informations d'identification à destination de l'employeur</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>LOIC001</Code>
<Description>Formulaire de demande d'interruption de carrière ou de crédit-temps</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>NOTI001</Code>
<Description>Notification en réponse à une déclaration</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>OSSA001</Code>
<Description>Attestation d'affiliation à la Sécurité Sociale d'Outre-mer qui indique pour quelle période une personne est assurée.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>OSSA002</Code>
<Description>Contrats et lettre d'accompagnement envoyés au souscripteur lors de son affiliation à la Sécurité Sociale d'Outre-mer.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>PFANS</Code>
<Description>Réponse à une demande de consultation de masse du fichier du personnel</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>PFREQ</Code>
<Description>Demande de consultation de masse du fichier du personnel</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>PPLCAL</Code>
<Description>Notification de calcul DMFAPPL</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>PPLUPD</Code>
<Description>Déclaration de modification relative à une déclaration multifonctionnelle concernant une administration provinciale ou locale</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>PROA001</Code>
<Description>Message reprenant les informations relatives aux échanges sur les actions de proactivité entreprises par les SSA ou à prendre par l'ONSS envers les employeurs</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>REDCOAN</Code>
<Description>Réponse à une demande de consultation de la dernière situation des déductions d'une déclaration multifonctionnelle</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>REDCORQ</Code>
<Description>Demande de consultation de la dernière situation des déductions d'une déclaration multifonctionnelle</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>RORE001</Code>
<Description>Règles de routage - communication des secrétariats sociaux et Full Service Center à la sécurité sociale, concernant la gestion des destinataires (et canaux) de messages.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2012</einde_geldigheid>
</ann11>
<ann11>
<Code>TWCT001</Code>
<Description>Communication de chômage temporaire par l'employeur</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>UWDUC</Code>
<Description>Déclaration unique de chantier</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>UWDUCUP</Code>
<Description>Déclaration de modification relative à une déclaration unique de chantier</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>VBLV001</Code>
<Description>Livre de validation chômage temporaire</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH001</Code>
<Description>Chômage scénario 1 - Déclaration de fin de contrat de travail ou de chômage avec complément d'entreprise / Preuve de travail</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH002</Code>
<Description>Chômage scénario 2 - Déclaration constat du droit au chômage temporaire ou à la suspension employés</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH003</Code>
<Description>Chômage scénario 3 - Déclaration de début de travail à temps partiel</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH004</Code>
<Description>Chômage scénario 4 - Déclaration de prépension à mi-temps</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2012</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH005</Code>
<Description>Chômage scénario 5 - Déclaration mensuelle d'heures de chômage temporaire ou de suspension employés</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH006</Code>
<Description>Chômage scénario 6 - Déclaration mensuelle de travail à temps partiel pour le calcul de l'allocation de garantie de revenus</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH007</Code>
<Description>Chômage scénario 7 - Déclaration mensuelle de travail en tant que travailleur occupé dans un atelier protégé</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH008</Code>
<Description>Chômage scénario 8 - Déclaration mensuelle de travail dans le cadre d'un programme d'activation</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH009</Code>
<Description>Chômage scénario 9 - Déclaration pour l'octroi du droit aux vacances jeunes ou seniors</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH010</Code>
<Description>Chômage scénario 10 - Déclaration mensuelle d'heures de vacances jeunes ou seniors</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>WECH011</Code>
<Description>Chômage scénario 11 - Déclaration mensuelle travail portuaire</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ZIMA001</Code>
<Description>Scénario 1 - Déclaration en cas d'incapacité de travail, de repos de maternité, d'écartement complet du travail en tant que mesure de protection de la maternité, d'écartement partiel du travail en tant que mesure de protection de la maternité, de congé maternité converti (art. 39, al. 6 loi du 16.3.1971 sur le travail), de congé de paternité ou de naissance (art. 30, § 2, loi du 3 juillet 1978 relative aux contrats de travail), de congé d'adoption et de congé parental d'accueil.</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ZIMA002</Code>
<Description>Indemnités scénario 2 - Déclaration mensuelle en cas de reprise d'un travail adapté dans le courant d'une période d'incapacité de travail, d'exercice d'un travail adapté dans le cadre d'une mesure de protection de la maternité [et (jusqu'au 31/12/2017) de poursuite d'une activité chez un des deux employeurs, lorsque la travailleuse est titulaire de deux emplois salariés auprès d'employeurs différents et n'est écartée du travail que du chef de l'une de ces deux occupations].</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ZIMA003</Code>
<Description>Indemnités scénario 3 - Attestation en vue de l'indemnisation des pauses d'allaitement</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ZIMA005</Code>
<Description>Indemnités scénario 5 - Déclaration annuelle de vacances</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
<ann11>
<Code>ZIMA006</Code>
<Description>Indemnités scénario 6 - Déclaration de reprise du travail</Description>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann11>
</List>
