<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann2 (TypeCodeTravailleur?, Code?, Description?, TypeTravailleur?, Présence?, Geldig_vanaf?, Geldig_tot?, begin_geldigheid?, einde_geldigheid?)>
     <!ELEMENT List (ann2+)>
     <!ELEMENT TypeCodeTravailleur (#PCDATA)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Description (#PCDATA)>
     <!ELEMENT TypeTravailleur (#PCDATA)>
     <!ELEMENT Présence (#PCDATA)>
     <!ELEMENT Geldig_vanaf (#PCDATA)>
     <!ELEMENT Geldig_tot (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>010</Code>
<Description>Travailleurs pensionnés visés par l'article 42 bis de la loi du 10 avril 1971 sur les accidents du travail et de par l'article 66 des lois coordonnées le 3 juin 1970 relatives à la prévention des maladies professionnelles et à la réparation des dommages résultant de celles-ci ou lorsque la victime a atteint l'âge de 65 ans.</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2015/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/10/2015</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>013</Code>
<Description>Jeunes défavorisés</Description>
<TypeTravailleur>Manuels spéciaux</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>014</Code>
<Description>Marins dans le secteur de la marine marchande,  des travaux de dragage ou du remorquage maritime</Description>
<TypeTravailleur>Marins</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2018/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/2018</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>015</Code>
<Description>Ouvriers et assimilés, y compris le personnel de maison</Description>
<TypeTravailleur>Ouvriers ordinaires</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>016</Code>
<Description>Mineurs</Description>
<TypeTravailleur>Mineurs (manuels)</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>027</Code>
<Description>Elèves-ouvriers et stagiaires</Description>
<TypeTravailleur>Elèves ouvriers ordinaires manuels</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>041</Code>
<Description>Domestiques victimes d'un accident du travail survenu avant le 01/04/1983</Description>
<TypeTravailleur>Domestiques (manuels)</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>045</Code>
<Description>Domestiques victimes d'un accident du travail à partir du 01/04/1983 ou de maladie professionnelle</Description>
<TypeTravailleur>Domestiques (manuels)</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>487</Code>
<Description>Elèves-employés et stagiaires</Description>
<TypeTravailleur>Intellectuels élèves</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>493</Code>
<Description>Médecins en formation de médecin spécialiste. Jeunes défavorisés. Boursiers originaires d'un pays hors Espace Economique Européen.</Description>
<TypeTravailleur>Intellectuels spéciaux</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>494</Code>
<Description>Sportifs rémunérés, sauf les coureurs cyclistes professionnels (détenteurs d'une licence de la ligue vélocipédique belge), victimes d'un accident du travail depuis le 01/01/1985</Description>
<TypeTravailleur>Intellectuels spéciaux</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>495</Code>
<Description>Travailleurs intellectuels et assimilés, employés de maison, ainsi que les coureurs cyclistes professionnels (détenteurs d'une licence de la ligue vélocipédique belge) victimes d'un accident du travail survenu depuis le 01/01/1985, parents d'accueil reconnus, artistes, travailleurs occasionnels de l'Horeca.</Description>
<TypeTravailleur>Intellectuels ordinaires</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation Fedris</TypeCodeTravailleur>
<Code>675</Code>
<Description>Travailleurs statutaires</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation membre du personnel statutaire exclusivement soumis à la cotisation de pension du secteur public</TypeCodeTravailleur>
<Code>676</Code>
<Description>Travailleurs statutaires avec lieu d'affectation à l'étranger</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>1</Présence>
<Geldig_vanaf>2015/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/2015</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation membre du personnel statutaire exclusivement soumis à la cotisation de pension du secteur public</TypeCodeTravailleur>
<Code>690</Code>
<Description>Médecins définitifs exonérés des cotisations de sécurité sociale sur base de l'art. 1er, § 3 de la loi du 27.6.1969 et qui, sur base de l'art. 158 de la loi relative aux hôpitaux du 10-07-2008, ont droit à une pension publique</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>1</Présence>
<Geldig_vanaf>2022/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/2022</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>802</Code>
<Description>Cotisation dans le cadre de l'allocation sociale II pour la police locale</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2022/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/2022</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>805</Code>
<Description>Cotisation de responsabilisation AGR - Allocation de garantie de revenus</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2020/2</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/04/2020</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>806</Code>
<Description>Cotisation de solidarité due sur les indemnités de voyage d'amarinage</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2018/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/10/2018</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>817</Code>
<Description>Cotisation d'égalisation due pour certains travailleurs statutaires et les mandataires locaux</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2015/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/2015</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>851</Code>
<Description>Cotisation spéciale due sur les versements effectués par les employeurs pour la constitution d'une pension extra-légale en faveur des membres de leur personnel ou de leurs ayants-droit</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>2011/3</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>30/09/2011</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>861</Code>
<Description>Cotisation due sur les participations aux bénéfices</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>862</Code>
<Description>Cotisation de solidarité sur l'usage d'un véhicule de société</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2005/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/2005</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>864</Code>
<Description>Cotisation spéciale due sur les versements effectués par les employeurs pour la constitution d'une pension extra-légale ; versements directs aux ex-travailleurs.</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2011/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/10/2011</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>865</Code>
<Description>Cotisation spéciale due sur les versements effectués par les employeurs pour la constitution d'une pension extra-légale ; versements dans le cadre d'un plan d'entreprise</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2011/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/10/2011</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>866</Code>
<Description>Cotisation spéciale due sur les versements effectués par les employeurs pour la constitution d'une pension extra-légale ; versements dans le cadre d'un plan sectoriel</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2011/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/10/2011</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>867</Code>
<Description>Cotisation spéciale supplémentaire due sur les versements effectués par les employeurs pour la constitution d'une pension extra-légale qui dépassent un montant déterminé</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2012/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/10/2012</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>870</Code>
<Description>Cotisation due sur le double pécule de vacances des employés et, au sein des administrations provinciales et locales, des contractuels et des stagiaires statutaires avec le régime de vacances du secteur privé, sur le pécule de vacances ou la prime Copernic des contractuels du secteur public fédéral et de la police locale  et sur la prime de restructuration des militaires contractuels</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation non liée à une personne physique</TypeCodeTravailleur>
<Code>875</Code>
<Description>Cotisation due sur le pécule de vacances octroyé par une administration provinciale ou locale aux contractuels avec le régime de vacances du secteur public et aux nommés dont la pension n'est pas à charge du Trésor public et ne relève pas du pool des parastataux</Description>
<TypeTravailleur>Autres (type travailleurs)</TypeTravailleur>
<Présence>4</Présence>
<Geldig_vanaf>2022/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/2022</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>010</Code>
<Description>Ouvriers temporaires dans l'horticulture et l'agriculture (employeurs immatriculés sous les catégories 194, 494, 594, 193, 293, 097 et 497) et jusqu'au deuxième trimestre 2007 inclus, ouvriers occasionnels dans l'Horeca (employeurs immatriculés sous les catégories 016, 017, 097 et 497).</Description>
<TypeTravailleur>Manuels saisonniers</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>011</Code>
<Description>Ouvriers de catégorie spéciale à déclarer sur base des rémunérations forfaitaires par des employeurs immatriculés sous les catégories 016, 017, 019, 116, 117, 216, 217 et, depuis le 1er trimestre 2010, 066, 323, 562 et 662 et, jusqu'au 1er trimestre 2007 inclus, 020, 023, 068, 146, 158, 166, 323 ou 562 (cotisation de modération salariale non due) et apprentis de cette catégorie à partir de l'année où ils atteignent 19 ans. A partir du quatrième trimestre 2013 aussi ouvriers de catégorie spéciale à déclarer sur base des rémunérations forfaitaires par des employeurs immatriculés sous les catégories 317, 097 et 497.</Description>
<TypeTravailleur>Manuels au forfait</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>012</Code>
<Description>Ouvriers handicapés et apprentis de cette catégorie à partir de l'année où ils atteignent 19 ans : a) Occupés dans un atelier protégé agréé immatriculé sous la catégorie 073, 173, 273 ou 473 (cotisation de modération salariale non due). b) Jusqu'au 3ème trimestre 2008 inclus, à déclarer par les employeurs immatriculés sous la catégorie 811 (cotisation de modération salariale due).</Description>
<TypeTravailleur>Manuels handicapés</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>013</Code>
<Description>a) Chauffeurs de taxi affectés au transport de personnes occupés par des employeurs immatriculés sous la catégorie 068 (cotisation de modération salariale non due) et apprentis de cette catégorie à partir de l'année où ils atteignent 19 ans. 
b) Ouvriers contractuels ne relevant pas du régime des vacances annuelles des salariés occupés par un employeur de la catégorie 040</Description>
<TypeTravailleur>Manuels spéciaux</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>014</Code>
<Description>Ouvriers de catégorie ordinaire pour qui la cotisation au Fonds Forestier est due par des employeurs immatriculés sous la catégorie 029 et apprentis de cette catégorie à partir de l'année où ils atteignent 19 ans.</Description>
<TypeTravailleur>Manuels ordinaires autre que les ouvriers</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>2019/1</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2019</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>015</Code>
<Description>Ouvriers de catégorie ordinaire et apprentis de cette catégorie à partir de l'année où ils atteignent 19 ans: a) à déclarer sur base des rémunérations proméritées par des employeurs immatriculés sous les catégories 016, 017, 019, 020, 023, 068, 158, 166 ou 562 (cotisation de modération salariale due); b) occasionnels déclarés sur base des rémunérations réelles par des employeurs immatriculés sous les catégories 116 et 117; c) non officiers déclarés par des employeurs immatriculés sous les catégories 105, 205, 305, 405 et 505; d) tous les autres ouvriers non mentionnés ailleurs.</Description>
<TypeTravailleur>Ouvriers ordinaires</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>016</Code>
<Description>Mineur travaillant en surface et apprentis de cette catégorie à partir de l'année où ils atteignent 19 ans.</Description>
<TypeTravailleur>Mineurs (manuels)</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>017</Code>
<Description>Mineur travaillant en sous-sol et apprentis de cette catégorie à partir de l'année où ils atteignent 19 ans.</Description>
<TypeTravailleur>Mineurs (manuels)</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>019</Code>
<Description>Apprentis et assimilés travailleurs manuels à partir de l'année où ils atteignent 19 ans déclarés  par des employeurs du secteur public immatriculés sous les catégories 001, 046, 050, 096, 296, 347, 351, 396, 441 et 496 (cotisations Fedris dues)</Description>
<TypeTravailleur>Manuels apprentis</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2005/3</Geldig_vanaf>
<Geldig_tot>2019/4</Geldig_tot>
<begin_geldigheid>01/07/2005</begin_geldigheid>
<einde_geldigheid>31/12/2019</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>020</Code>
<Description>Elèves ouvriers de catégorie spéciale (voir code 010 dans catégories 016, 017, 097 et 497) jusqu'au 31 décembre de l'année où ils atteignent 18 ans.</Description>
<TypeTravailleur>Manuels Horeca autres que les saisonniers</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/3</Geldig_vanaf>
<Geldig_tot>2007/2</Geldig_tot>
<begin_geldigheid>01/07/2003</begin_geldigheid>
<einde_geldigheid>30/06/2007</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>020</Code>
<Description>Elèves ouvriers occasionnels de catégorie spéciale (voir code 011 dans catégories 317, 097 et 497) jusqu'au 31 décembre de l'année où ils atteignent 18 ans.</Description>
<TypeTravailleur>Manuels occasionnels Horeca</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2013/4</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/10/2013</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>021</Code>
<Description>Travailleurs contractuels - ouvriers engagés dans le secteur public en remplacement de travailleurs contractuels ou statutaires en interruption de carrière selon les dispositions de la loi de redressement du 22 janvier 1985 ou en remplacement de travailleurs qui réduisent leurs prestations de 1/5e avec prime compensatoire dans le cadre de la redistribution du travail dans le secteur public.</Description>
<TypeTravailleur>Manuels contractuels remplaçants</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2014/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/2014</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>022</Code>
<Description>Elèves-ouvriers stagiaires de catégorie spéciale (voir code 011 et code 010 jusqu'au 2ème trimestre 2007 inclus à l'exception des occasionnels ("super extras") de l'Horeca) ) jusqu'au 31 décembre de l'année où ils atteignent 18 ans.</Description>
<TypeTravailleur>Autres élèves manuels</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>024</Code>
<Description>Contractuels subventionnés, travailleurs manuels déclarés sur base d'une rémunération réelle (voir code 015 points b) et c))</Description>
<TypeTravailleur>Manuels contractuels subventionnés</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>025</Code>
<Description>Contractuels subventionnés, travailleurs manuels handicapés déclarés sur base d'une rémunération réelle, occupés dans des ateliers protégés</Description>
<TypeTravailleur>Manuels contractuels subventionnés</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>026</Code>
<Description>Elèves ouvriers et stagiaires de catégorie ordinaire (voir code 014) jusqu'au 31 décembre de l'année où ils atteignent 18 ans.</Description>
<TypeTravailleur>Autres élèves manuels</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>2019/1</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>31/03/2019</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>027</Code>
<Description>Elèves ouvriers et stagiaires de catégorie ordinaire (voir code 015) jusqu'au 31 décembre de l'année où ils atteignent 18 ans.</Description>
<TypeTravailleur>Elèves ouvriers ordinaires manuels</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>029</Code>
<Description>Contractuels subventionnés, travailleurs manuels déclarés sur base d'une rémunération forfaitaire occupés par les pouvoirs publics et autres établissements, associations et sociétés assimilés</Description>
<TypeTravailleur>Manuels contractuels subventionnés</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>035</Code>
<Description>Apprentis et assimilés travailleurs manuels jusqu'au 31 décembre de l'année où ils atteignent 18 ans.</Description>
<TypeTravailleur>Manuels apprentis</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>043</Code>
<Description>Personnel de maison, travailleurs manuels, déclarés par des employeurs immatriculés sous les catégories 039, 094, 193, 099 et 299.</Description>
<TypeTravailleur>Manuels spéciaux</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2010/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/07/2010</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>044</Code>
<Description>Personnel de maison, élèves ouvriers (voir code 043) jusqu'au 31 décembre de l'année où ils atteignent 18 ans.</Description>
<TypeTravailleur>Élèves manuels spéciaux</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2010/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/07/2010</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>045</Code>
<Description>Domestiques déclarés par des employeurs immatriculés sous la catégorie 037 ou 437</Description>
<TypeTravailleur>Domestiques (manuels)</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/1</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/01/1900</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>046</Code>
<Description>Artistes et apprentis de cette catégorie à partir de l'année où ils atteignent 19 ans.</Description>
<TypeTravailleur>Autres travailleurs artistes</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/07/2003</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>047</Code>
<Description>Artistes - Elèves à temps partiel jusqu'au 31 décembre de l'année où ils atteignent 18 ans.</Description>
<TypeTravailleur>Elèves artistes</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2003/3</Geldig_vanaf>
<Geldig_tot>9999/4</Geldig_tot>
<begin_geldigheid>01/07/2003</begin_geldigheid>
<einde_geldigheid>01/01/9999</einde_geldigheid>
</ann2>
<ann2>
<TypeCodeTravailleur>Cotisation ordinaire</TypeCodeTravailleur>
<Code>050</Code>
<Description>Travailleurs manuels occupés dans le cadre d'un flexijob</Description>
<TypeTravailleur>Travailleurs manuels flexijob</TypeTravailleur>
<Présence>3</Présence>
<Geldig_vanaf>2015/4</Geldig_vanaf>