<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann4 (CodeDMFA?, Omschrijving?, Vanaf?, Tot?
	        , Ded_FedRegNL?, Ded_FlemishRegNL?, Ded_BxlRegNL?
	        , Ded_WallNoGermanRegNL?, Ded_WallGermanRegNL?
	        , CalcBaseNl?, AmountNl?, StartRightNl?, MnthCostNl?
	        , InssNbrReplNl?, InssNbrAuthNl?, OrigAttNl?
	        , LinkBlocNl?, PresBlcDetNl?)>
     <!ELEMENT List (ann4+)>
     <!ELEMENT CodeDMFA (#PCDATA)>
     <!ELEMENT Omschrijving (#PCDATA)>
     <!ELEMENT Vanaf (#PCDATA)>
     <!ELEMENT Tot (#PCDATA)>
     <!ELEMENT Ded_FedRegNL (#PCDATA)>
     <!ELEMENT Ded_FlemishRegNL (#PCDATA)>
     <!ELEMENT Ded_BxlRegNL (#PCDATA)>
     <!ELEMENT Ded_WallNoGermanRegNL (#PCDATA)>
     <!ELEMENT Ded_WallGermanRegNL (#PCDATA)>
     <!ELEMENT CalcBaseNl (#PCDATA)>
     <!ELEMENT AmountNl (#PCDATA)>
     <!ELEMENT StartRightNl (#PCDATA)>
     <!ELEMENT MnthCostNl (#PCDATA)>
     <!ELEMENT InssNbrReplNl (#PCDATA)>
     <!ELEMENT InssNbrAuthNl (#PCDATA)>
     <!ELEMENT OrigAttNl (#PCDATA)>
     <!ELEMENT LinkBlocNl (#PCDATA)>
     <!ELEMENT PresBlcDetNl (#PCDATA)>
]>
<List>
    <ann4>
        <CodeDMFA>0001</CodeDMFA>
        <Omschrijving>Vermindering van de persoonlijke bijdragen voor de werknemers met een werkbonus</Omschrijving>
        <Vanaf>2000/1</Vanaf>
        <Tot>9999/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verboden</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>0501</CodeDMFA>
        <Omschrijving>Vermindering van de persoonlijke bijdragen in de baggersector</Omschrijving>
        <Vanaf>2000/1</Vanaf>
        <Tot>2014/2</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verboden</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>0600</CodeDMFA>
        <Omschrijving>Vermindering van de persoonlijke bijdragen voor werknemers ontslagen in het kader van een herstructurering - arbeidsovereenkomst afgesloten voor 1.1.2007</Omschrijving>
        <Vanaf>2004/3</Vanaf>
        <Tot>2007/2</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verboden</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>0601</CodeDMFA>
        <Omschrijving>Vermindering van de persoonlijke bijdragen voor werknemers ontslagen in het kader van een herstructurering</Omschrijving>
        <Vanaf>2007/1</Vanaf>
        <Tot>9999/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>0610</CodeDMFA>
        <Omschrijving>Sportbonus</Omschrijving>
        <Vanaf>2022/1</Vanaf>
        <Tot>9999/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verboden</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>0611</CodeDMFA>
        <Omschrijving>Vermindering van de persoonlijke bijdragen voor gepensioneerden die werken in de zorgsector</Omschrijving>
        <Vanaf>2022/3</Vanaf>
        <Tot>2022/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verboden</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1001</CodeDMFA>
        <Omschrijving>Structurele vermindering</Omschrijving>
        <Vanaf>1999/1</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verboden</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1101</CodeDMFA>
        <Omschrijving>Banenplan voor werkzoekenden die beantwoorden aan de voorwaarde van 12 maanden</Omschrijving>
        <Vanaf>1995/1</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1101</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Banenplan voor werkzoekenden die beantwoorden aan de voorwaarde van 12 maanden</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2004/1</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1102</CodeDMFA>
        <Omschrijving>Banenplan voor werkzoekenden die beantwoorden aan de voorwaarde van 24 maanden</Omschrijving>
        <Vanaf>1995/1</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1102</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Banenplan voor werkzoekenden die beantwoorden aan de voorwaarde van 24 maanden</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2004/1</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1103</CodeDMFA>
        <Omschrijving>Banenplan voor werkzoekenden - inschakelingsbedrijven</Omschrijving>
        <Vanaf>1996/3</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1103</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Banenplan voor werkzoekenden - inschakelingsbedrijven</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2007/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1104</CodeDMFA>
        <Omschrijving>Banenplan voor werkzoekenden ouder dan 50 jaar</Omschrijving>
        <Vanaf>1996/1</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1105</CodeDMFA>
        <Omschrijving>Banenplan voor werkzoekenden die beantwoorden aan de voorwaarde van 12 maanden (&gt;45 jaar)</Omschrijving>
        <Vanaf>2000/3</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1105</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Banenplan voor werkzoekenden die beantwoorden aan de voorwaarde van 12 maanden (&gt;45 jaar)</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2008/1</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1106</CodeDMFA>
        <Omschrijving>Banenplan voor werkzoekenden die beantwoorden aan de voorwaarde van 24 maanden (&gt;45 jaar)</Omschrijving>
        <Vanaf>2000/3</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1106</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Banenplan voor werkzoekenden die beantwoorden aan de voorwaarde van 24 maanden (&gt;45 jaar)</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2008/1</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1111</CodeDMFA>
        <Omschrijving>Activaplan - bevordering van de tewerkstelling van langdurig werkzoekenden  - 75%</Omschrijving>
        <Vanaf>2002/1</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1111</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Activaplan afgesloten voor 1.1.2004 - bevordering van de tewerkstelling van langdurig werkzoekenden  - 75%</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2008/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1112</CodeDMFA>
        <Omschrijving>Activaplan - bevordering van de tewerkstelling van langdurig werkzoekenden  - 100%</Omschrijving>
        <Vanaf>2002/1</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1112</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Activaplan afgesloten voor 1.1.2004 - bevordering van de tewerkstelling van langdurig werkzoekenden - 100%</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2008/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1121</CodeDMFA>
        <Omschrijving>Plus-één-plan</Omschrijving>
        <Vanaf>1994/1</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Optioneel</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1121</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Plus-één-plan</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2006/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1122</CodeDMFA>
        <Omschrijving>Plus-twee-plan</Omschrijving>
        <Vanaf>1997/1</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Optioneel</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1122</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Plus-twee-plan</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2006/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1123</CodeDMFA>
        <Omschrijving>Plus-drie-plan</Omschrijving>
        <Vanaf>1997/1</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Optioneel</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1123</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Plus-drie-plan</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2005/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1124</CodeDMFA>
        <Omschrijving>Plus-één-plan - gewezen interimaris</Omschrijving>
        <Vanaf>1998/4</Vanaf>
        <Tot>2003/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verplicht</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Optioneel</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
    <ann4>
        <CodeDMFA>1124</CodeDMFA>
        <Omschrijving>Overgangsperiode.  Plus-één-plan - gewezen interimaris</Omschrijving>
        <Vanaf>2004/1</Vanaf>
        <Tot>2006/4</Tot>
        <Ded_FedRegNL>Federaal</Ded_FedRegNL>
        <Ded_FlemishRegNL>-</Ded_FlemishRegNL>
        <Ded_BxlRegNL>-</Ded_BxlRegNL>
        <Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
        <Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
        <CalcBaseNl>Verboden</CalcBaseNl>
        <AmountNl>Verplicht</AmountNl>
        <StartRightNl>Verplicht</StartRightNl>
        <MnthCostNl>Verboden</MnthCostNl>
        <InssNbrReplNl>Verboden</InssNbrReplNl>
        <InssNbrAuthNl>Verboden</InssNbrAuthNl>
        <OrigAttNl>Optioneel</OrigAttNl>
        <LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
        <PresBlcDetNl>Neen</PresBlcDetNl>
    </ann4>
<ann4>
<CodeDMFA>1125</CodeDMFA>
<Omschrijving>Plus-twee-plan - gewezen interimaris</Omschrijving>
<Vanaf>1998/4</Vanaf>
<Tot>2003/4</Tot>
<Ded_FedRegNL>Federaal</Ded_FedRegNL>
<Ded_FlemishRegNL>-</Ded_FlemishRegNL>
<Ded_BxlRegNL>-</Ded_BxlRegNL>
<Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
<Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
<CalcBaseNl>Verplicht</CalcBaseNl>
<AmountNl>Verplicht</AmountNl>
<StartRightNl>Verplicht</StartRightNl>
<MnthCostNl>Verboden</MnthCostNl>
<InssNbrReplNl>Verboden</InssNbrReplNl>
<InssNbrAuthNl>Optioneel</InssNbrAuthNl>
<OrigAttNl>Optioneel</OrigAttNl>
<LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
<PresBlcDetNl>Neen</PresBlcDetNl>
</ann4>
<ann4>
<CodeDMFA>1125</CodeDMFA>
<Omschrijving>Overgangsperiode.  Plus-twee-plan - gewezen interimaris</Omschrijving>
<Vanaf>2004/1</Vanaf>
<Tot>2006/4</Tot>
<Ded_FedRegNL>Federaal</Ded_FedRegNL>
<Ded_FlemishRegNL>-</Ded_FlemishRegNL>
<Ded_BxlRegNL>-</Ded_BxlRegNL>
<Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
<Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
<CalcBaseNl>Verboden</CalcBaseNl>
<AmountNl>Verplicht</AmountNl>
<StartRightNl>Verplicht</StartRightNl>
<MnthCostNl>Verboden</MnthCostNl>
<InssNbrReplNl>Verboden</InssNbrReplNl>
<InssNbrAuthNl>Verboden</InssNbrAuthNl>
<OrigAttNl>Optioneel</OrigAttNl>
<LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
<PresBlcDetNl>Neen</PresBlcDetNl>
</ann4>
<ann4>
<CodeDMFA>1126</CodeDMFA>
<Omschrijving>Plus-drie-plan - gewezen interimaris</Omschrijving>
<Vanaf>1998/4</Vanaf>
<Tot>2003/4</Tot>
<Ded_FedRegNL>Federaal</Ded_FedRegNL>
<Ded_FlemishRegNL>-</Ded_FlemishRegNL>
<Ded_BxlRegNL>-</Ded_BxlRegNL>
<Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
<Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
<CalcBaseNl>Verplicht</CalcBaseNl>
<AmountNl>Verplicht</AmountNl>
<StartRightNl>Verplicht</StartRightNl>
<MnthCostNl>Verboden</MnthCostNl>
<InssNbrReplNl>Verboden</InssNbrReplNl>
<InssNbrAuthNl>Optioneel</InssNbrAuthNl>
<OrigAttNl>Optioneel</OrigAttNl>
<LinkBlocNl>Tewerkstelling van de werknemerslijn</LinkBlocNl>
<PresBlcDetNl>Neen</PresBlcDetNl>
</ann4>
<ann4>
<CodeDMFA>1126</CodeDMFA>
<Omschrijving>Overgangsperiode.  Plus-drie-plan - gewezen interimaris</Omschrijving>
<Vanaf>2004/1</Vanaf>
<Tot>2005/4</Tot>
<Ded_FedRegNL>Federaal</Ded_FedRegNL>
<Ded_FlemishRegNL>-</Ded_FlemishRegNL>
<Ded_BxlRegNL>-</Ded_BxlRegNL>
<Ded_WallNoGermanRegNL>-</Ded_WallNoGermanRegNL>
<Ded_WallGermanRegNL>-</Ded_WallGermanRegNL>
<CalcBaseNl>Verboden</CalcBaseNl>
<AmountNl>Verplicht</AmountNl>