<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE List [
     <!ELEMENT ann10 (werkgeverscategorienummer?, Code?
	        , Description?, Remarquebijlage10?, begin_geldigheid?
	        , einde_geldigheid?)>
     <!ELEMENT List (ann10+)>

     <!ELEMENT werkgeverscategorienummer (#PCDATA)>
     <!ELEMENT Code (#PCDATA)>
     <!ELEMENT Description (#PCDATA)>
     <!ELEMENT Remarquebijlage10 (#PCDATA)>
     <!ELEMENT begin_geldigheid (#PCDATA)>
     <!ELEMENT einde_geldigheid (#PCDATA)>
]>
<List>

    <ann10>
        <werkgeverscategorienummer>027</werkgeverscategorienummer>
        <Code>01</Code>
        <Description>Indemnit� journali�re</Description>
        <begin_geldigheid>1/01/1900</begin_geldigheid>
        <einde_geldigheid>1/01/9999</einde_geldigheid>
    </ann10>
    <ann10>
        <werkgeverscategorienummer>027</werkgeverscategorienummer>
        <Code>02</Code>
        <Description>Allocation annuelle</Description>
        <begin_geldigheid>1/01/1900</begin_geldigheid>
        <einde_geldigheid>1/01/9999</einde_geldigheid>
    </ann10>
    <ann10>
        <werkgeverscategorienummer>027</werkgeverscategorienummer>
        <Code>03</Code>
        <Description>Rente</Description>
        <begin_geldigheid>1/01/1900</begin_geldigheid>
        <einde_geldigheid>1/01/9999</einde_geldigheid>
    </ann10>
    <ann10>
        <werkgeverscategorienummer>027</werkgeverscategorienummer>
        <Code>04</Code>
        <Description>Capital</Description>
        <begin_geldigheid>1/01/1900</begin_geldigheid>
        <einde_geldigheid>1/01/9999</einde_geldigheid>
    </ann10>
    <ann10>
        <werkgeverscategorienummer>027</werkgeverscategorienummer>
        <Code>05</Code>
        <Description>Allocation</Description>
        <begin_geldigheid>1/01/1900</begin_geldigheid>
        <einde_geldigheid>1/01/9999</einde_geldigheid>
    </ann10>
    <ann10>
    <werkgeverscategorienummer>027</werkgeverscategorienummer>
    <Code>12</Code>
    <Description>Allocation annuelle avec un degr� d'incapacit� &lt; � 10 %</Description>
    <Remarquebijlage10>Ces codes ne peuvent �tre utilis�s qu�en cas d�exception c.�.d. lorsqu�on a l�autorisation l�gale de faire la d�claration une seule fois par ann�e. La d�claration d�un travailleur avec un degr� d�incapacit� &lt; � 10 % doit de pr�f�rence �tre faite une fois par trimestre en utilisant les codes 01 � 05.</Remarquebijlage10>
    <begin_geldigheid>1/01/1900</begin_geldigheid>
    <einde_geldigheid>1/01/9999</einde_geldigheid>
    </ann10>
    <ann10>
    <werkgeverscategorienummer>027</werkgeverscategorienummer>
    <Code>13</Code>
    <Description>Rente avec un degr� d'incapacit� &lt; � 10 %</Description>
    <Remarquebijlage10>Ces codes ne peuvent �tre utilis�s qu�en cas d�exception c.�.d. lorsqu�on a l�autorisation l�gale de faire la d�claration une seule fois par ann�e. La d�claration d�un travailleur avec un degr� d�incapacit� &lt; � 10 % doit de pr�f�rence �tre faite une fois par trimestre en utilisant les codes 01 � 05.</Remarquebijlage10>
    <begin_geldigheid>1/01/1900</begin_geldigheid>
    <einde_geldigheid>1/01/9999</einde_geldigheid>
    </ann10>
    <ann10>
    <werkgeverscategorienummer>027</werkgeverscategorienummer>
    <Code>15</Code>
    <Description>Allocation avec un degr� d'incapacit� &lt; � 10 %</Description>
    <Remarquebijlage10>Ces codes ne peuvent �tre utilis�s qu�en cas d�exception c.�.d. lorsqu�on a l�autorisation l�gale de faire la d�claration une seule fois par ann�e. La d�claration d�un travailleur avec un degr� d�incapacit� &lt; � 10 % doit de pr�f�rence �tre faite une fois par trimestre en utilisant les codes 01 � 05.</Remarquebijlage10>
    <begin_geldigheid>1/01/1900</begin_geldigheid>
    <einde_geldigheid>1/01/9999</einde_geldigheid>
    </ann10>
    <ann10>
    <werkgeverscategorienummer>028</werkgeverscategorienummer>
    <Code>00</Code>
    <Description>Toutes indemnit�s</Description>
    <Remarquebijlage10>Concerne uniquement le Fonds des Maladies Professionnelles</Remarquebijlage10>
    <begin_geldigheid>1/01/1900</begin_geldigheid>
    <einde_geldigheid>1/01/9999</einde_geldigheid>
    </ann10>
</List>

